version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
workflows:
  - steps:
    - run:
        name: Copy across app.yaml config
        command: ./app.yaml.sh > ./app.yaml
    - heroku_deploy:
        jobs:
          - heroku/deploy-via-git