version: 2.1
orbs:
  dotenv: anilanar/dotenv@volatile
jobs:
  build:
    docker:
      - image: 'circleci/node:8.17'
    working_directory: ~/repo
    steps:
      - checkout
      - dotenv/source:
          path: .env
      - run: make build
orbs:
  heroku: circleci/heroku@0.0.10
workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git