version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
workflows:
  heroku_deploy:
    jobs:
      - run:
          name: Copy across app.yaml config
          command: ./app.yaml.sh > ./app.yaml
      - heroku/deploy-via-git